name: "Publish Reports"
description: "Annotates files feeding from JUnit/AndroidLint/Checkstyle XML reports"
inputs:
  token:
    description: "Specify the token to use to publish the check (required unless you set `appId` and `appSecret`)"
    required: false
    default: ${{ github.token }}
  appId:
    description: "A GitHub App ID to use to publish the check (required unless you set `token`)"
    required: false
  appSecret:
    description: "A GitHub App secret (private key) to use to publish the check (required unless you set `token`)"
    required: false
  checkName:
    description: "Check name for test reports (only annotates if missing)"
    required: false
  reports:
    description: "A multiline list of glob paths to report XML files"
    required: true
    default: |
      **/build/test-results/**/*.xml
      **/build/reports/**/*.xml
  testsSummary:
    description: "The kind summary to report for the tests found: `full` (default), `suitesOnly`, `totals` or `off`"
    required: true
    default: "full"
  checksSummary:
    description: "The kind summary to report for the checks found: `full` (default), `totals`, `off`"
    required: true
    default: "full"
  filterPassedTests:
    description: "tests (suites and cases) that has passed from reporting into the summary"
    required: true
    default: "false"
  filterChecks:
    description: "Report only check annotations coming from files that have been changed in the PR (tests won't be filtered)"
    required: false
    default: "false"
  detectFlakyTests:
    description: "If multiple test reports matching `className` and `name` are found, they will be assumed re-tries. If at least once of those passes, the test is considered flaky and passed."
    required: false
    default: "false"
  warningsAsErrors:
    description: "Treat warnings as errors"
    required: false
    default: "false"
  failOnError:
    description: "Fail the action if any errors are found"
    required: false
    default: "false"
runs:
  using: node20
  main: dist/index.js
branding:
  color: green
  icon: list
