name: 'Setup Host'
description: 'Configures the host runner to run the build'

runs:
  using: "composite"
  steps:
    - name: Setup Xcode
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: xcodes select $(xcodes installed | tail -n1 | grep -Eo '^\S+')
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Install NPM dependencies
      shell: bash
      run: npm ci
